// <auto-generated />
using System;
using FBMMultiMessenger.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBMMultiMessenger.Migrations
{
    [DbContext(typeof(MessengerDbContext))]
    [Migration("20260225073839_UniqueIndexInChat")]
    partial class UniqueIndexInChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FbAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FBChatId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FBListingImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FbAccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FbListingId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FbListingLocation")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FbListingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("FbListingTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("FbUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtherUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserProfileImage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("FBChatId", "UserId")
                        .IsUnique();

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.ChatMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FBTimestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FbMessageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FbMessageReplyId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAudioMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsImageMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTextMessage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVideoMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("FBTimestamp");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.SyncMeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SyncMeta");
                });

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.Chat", b =>
                {
                    b.HasOne("FBMMultiMessenger.Database.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.ChatMessages", b =>
                {
                    b.HasOne("FBMMultiMessenger.Database.Models.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("FBMMultiMessenger.Database.Models.Chat", b =>
                {
                    b.Navigation("ChatMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
